---

- name: Add entries into /etc/hosts file
  lineinfile:
    path: /etc/hosts
    regexp: "^{{ item }}"
    line: "{{ item }}"
    unsafe_writes: true  # to prevent failures in CI
  loop: "{{ etc_hosts }}"
  when:
    - etc_hosts is defined
    - etc_hosts | length > 0

- name: Add entries into /etc/cloud/templates/hosts.redhat.tmpl file
  lineinfile:
    path: /etc/cloud/templates/hosts.redhat.tmpl
    regexp: "^{{ item }}"
    line: "{{ item }}"
    unsafe_writes: true  # to prevent failures in CI
  loop: "{{ etc_hosts }}"
  when:
    - etc_hosts is defined
    - etc_hosts | length > 0


...
