---
- name: Initial setup VM
  hosts: localhost
  vars_files:
    - vms.yml
  tasks:
    # - name: Clone VMs
    #   proxmox_kvm:
    #     node:         "{{ node }}"
    #     name:         "{{ item.value.name }}"
    #     newid:        "{{ item.value.vmid }}"
    #     api_user:     "{{ api_user }}"
    #     api_password: "{{ api_password }}"
    #     api_host:     "{{ api_host }}"
    #     clone:        "{{ clone_vm }}"
    #     # full:         yes
    #   loop: "{{ lookup('dict', vms) }}"

    # - name: Set IP addresses and change bridge DMZ
    #   shell: |
    #     ssh root@192.168.2.2 'qm set {{ item.value.vmid }} --ipconfig0 ip={{ item.value.ipaddress }},gw={{ item.value.gateway }}'
    #     ssh root@192.168.2.2 'qm set {{ item.value.vmid }} --net0 "model=virtio,bridge=vmbr2"'
    #   loop: "{{ lookup('dict', vms) }}"

    # - name: Remove lv
    #   shell: |
    #     ssh root@192.168.2.2 'lvremove /dev/pve/vm-{{ item.value.vmid }}-disk-1 --force'
    #   loop: "{{ lookup('dict', vms) }}"
    #   when: 
    #     - item.value.vmid == 1120
    #     - item.value.vmid == 1121
    #     - item.value.vmid == 1122

    - name: Add additional disk scsi1 size=500G
      shell: |
        ssh root@192.168.2.2 'qm set {{ item.value.vmid }} --scsi1 local-lvm:500'
      loop: "{{ lookup('dict', vms) }}"
      # delegate_to: 127.0.0.1
      # run_once: true
      # when: item.value.vmid == "1120" or item.value.vmid == "1121" or item.value.vmid == "1122"
      # when: item.value.vmid == "1120"
    
    # - name: Shows facts
    #   ansible.builtin.debug:
    #     var: item.value.vmid
    #   loop: "{{ lookup('dict', vms) }}"

    # - name: Update VMs
    #   proxmox_kvm:
    #     api_host:     "{{ api_host }}"
    #     api_user:     "{{ api_user }}"
    #     api_password: "{{ api_password }}"
    #     # scsi:         '{ "scsi1":"local-lvm:500G" }' # не работает, разработчик отключил эту возможность, из cli: `qm set 1132 --scsi1 local-lvm:500`
    #     cores:        "{{ item.value.cores }}"
    #     sockets:      "{{ item.value.sockets }}"
    #     memory:       "{{ item.value.memory }}"
    #     # revert:
    #     update:       yes
    #     # bootdisk:     scsi0
    #     vga:          serial0
    #     # net:          '{ "net0" : "model=virtio,bridge=vmbr2" }' # не работает, разработчик отключил эту возможность
    #     vmid:         "{{ item.value.vmid }}"
    #     node:         "{{ node }}"
    #     name:         "{{ item.value.name }}"
    #   loop: "{{ lookup('dict', vms) }}"

    # - name: Start VMs
    #   proxmox_kvm:
    #     api_host:     "{{ api_host }}"
    #     api_password: "{{ api_password }}"
    #     api_user:     "{{ api_user }}"
    #     vmid:         "{{ item.value.vmid }}"
    #     node:         "{{ node }}"
    #     state:        started
    #   loop: "{{ lookup('dict', vms) }}"