---
- name: prepare | set timezone to Europe/Moscow
  ansible.builtin.timezone:
    name: Europe/Moscow

- name: prepare | install dependencies
  ansible.builtin.yum:
    name:
      - lvm2
      - centos-release-gluster
      - firewalld
      - python3-pip
    state: present

- name: prepare | install dependencies for pexpect
  ansible.builtin.yum:
    name:
      - python3-pip
    state: present
  delegate_to: "{{ master_ghost }}"

- name: Install dependencies
  pip:
    name: pexpect>=3.3
    executable: pip3

- name: Install dependencies for pexpect
  pip:
    name: pexpect>=3.3
    executable: pip3
  delegate_to: "{{ master_ghost }}"

- name: prepare | install gluster-server
  ansible.builtin.yum:
    name: glusterfs-server
    state: present

- name: prepare | enable and start unit glusterd
  ansible.builtin.systemd:
    name: glusterd
    enabled: true
    state: started

    
